---

- name: remove not needed packages
  yum:
    name: "{{ firewall_packages_remove }}"
    state: absent

- name: install needed packages
  yum:
    name: "{{ firewall_packages_add }}"
    state: present
  notify: restart nftables

- name: enable nftables
  service:
    name: nftables
    enabled: yes
    state: started

...