---

- name: enable main.nft include
  lineinfile:
    path: /etc/sysconfig/nftables.conf
    line: include "/etc/nftables/main.nft"
    regexp: '^#*include "\/etc\/nftables\/main.nft"$'
  notify: restart nftables

- name: create conf.d
  file:
    state: directory
    path: /etc/nftables/conf.d
    owner: root
    group: root

- name: generate main.nft
  template: 
    src: nftables.nft.j2
    dest: /etc/nftables/main.nft
  when: firewall_table_name is not defined or firewall_table_name is none
  notify: restart nftables

- name: generate custom.nft
  template: 
    src: nftables.nft.j2
    dest: /etc/nftables/conf.d/{{ firewall_table_name }}.nft
  when: firewall_table_name is defined and firewall_table_name is not none
  notify: restart nftables

- name: activate ipv4 forwarding on boot
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
  register: forward_boot

- name: activate ipv4 forwarding now
  shell: "sysctl -w net.ipv4.ip_forward=1"
  when: forward_boot.changed

...