---

- name: Check MD5 sum
  shell: test -f /etc/sysconfig/iptables.ansible_md5 || md5sum /etc/sysconfig/iptables > /etc/sysconfig/iptables.ansible_md5 ; md5sum --check /etc/sysconfig/iptables.ansible_md5 > /dev/null 2>&1 && echo "true" || echo "false"
  register: iptables_stats

- name: generate iptables set
  template: 
    src: iptables.j2
    dest: /etc/sysconfig/iptables
  notify: restart iptables
  when: iptables_stats.stdout == "true"

- name: debug msg
  debug:
    msg: "IPTABLES HAS BEEN MANUALLY CHANGED"
  failed_when: iptables_stats.stdout == "false"
  ignore_errors: yes
  when: iptables_stats.stdout == "false"

- name: generate MD5 sum
  shell: md5sum /etc/sysconfig/iptables > /etc/sysconfig/iptables.ansible_md5
  register: iptables_stats
  when: iptables_stats.stdout == "true"
  
- name: activate ipv4 forwarding on boot
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
  register: forward_boot

- name: activate ipv4 forwarding now
  shell: "sysctl -w net.ipv4.ip_forward=1"
  when: forward_boot.changed

...