---

- name: generate iptables set
  template: 
    src: iptables.j2
    dest: /etc/sysconfig/iptables
  notify: restart iptables

- name: activate ipv4 forwarding on boot
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
  register: forward_boot

- name: activate ipv4 forwarding now
  shell: "sysctl -w net.ipv4.ip_forward=1"
  when: forward_boot.changed

...