---

- name: generate command
  set_fact:
    nft_command: "oifname \"{{ item.interface }}\" snat to {{ item.ip }}"

- name: check if rule exists
  shell: nft list chain default POSTROUTING | grep "{{ nft_command }}" && echo "1" || echo "0"
  register: nft_ruleset_cmd
  changed_when: false     
  
- name: run command
  shell: nft add rule default POSTROUTING {{ nft_command }}
  when: nft_ruleset_cmd.stdout == "0"

- name: save nftables
  shell: nft list ruleset > /etc/nftables/main.nft
  when: nft_ruleset_cmd.stdout == "0"

...